### ISSUE TITLE
Web platform exception

### ISSUE THREAD

**Issue by hasanm08** [seel-channel/video_viewer#24]
Error: PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided.,
The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)

    at Object.createErrorWithStack (http://localhost:12595/dart_sdk.js:5050:12)
    at Object._rethrow (http://localhost:12595/dart_sdk.js:37641:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:12595/dart_sdk.js:37637:13)
    at Object._microtaskLoop (http://localhost:12595/dart_sdk.js:37497:13)
    at _startMicrotaskLoop (http://localhost:12595/dart_sdk.js:37503:13)
    at http://localhost:12595/dart_sdk.js:33274:9

**Comment by seel-channel** [comment]
Some videos are no supported or has bugs on play. Your video format isn't web compatible. Check the formats compatibles in the link below

[Web  Media Formats File Types](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#index_of_media_container_formats_file_types)

**Comment by hasanm08** [comment]
yes, I think I played HLS format.
