### ISSUE TITLE
Youtube support

### ISSUE THREAD

**Issue by C4st3ll4n** [seel-channel/video_viewer#58]
Does the lib support youtube videos also ?

**Comment by C4st3ll4n** [comment]
Cause I've trying to use this lib with youtube's videos and it doesn't work
```

E/ExoPlayerImplInternal( 3854):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 3854):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:640)
E/ExoPlayerImplInternal( 3854):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:610)
E/ExoPlayerImplInternal( 3854):       at android.os.Handler.dispatchMessage(Handler.java:106)
E/ExoPlayerImplInternal( 3854):       at android.os.Looper.loop(Looper.java:203)
E/ExoPlayerImplInternal( 3854):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 3854):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
E/ExoPlayerImplInternal( 3854):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal( 3854):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1020)
E/ExoPlayerImplInternal( 3854):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal( 3854):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/ExoPlayerImplInternal( 3854):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/ExoPlayerImplInternal( 3854):       at java.lang.Thread.run(Thread.java:761)
E/flutter ( 3854): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter ( 3854): 

```

**Comment by akshaykumaru18** [comment]
hey have you found any solution?
